security:
  user:
    password: password
broker:
  username: 131336456698641549-admin
  password: YzMwYmVhMDdlZDM2YzMzMWNhM2Y0YjIxM2JiNmRhYzg=
  namespace: 131336456698641549
  replication-group: ecstestdrivegeo
  management-endpoint: https://portal.ecstestdrive.com
  object-endpoint: https://object.ecstestdrive.com
  repository-user: 131336456698641549@ecstestdrive.emc.com
catalog:
  services:
    - id: 09cac1c6-1b0a-11e6-b6ba-3e1d05defe78
      name: ecs-namespace
      description: Elastic Cloud Namespace
      bindable: true
      plan-updatable: true
      tags:
        - ecs-store
        - object
      service-settings:
        service-type: namespace
      metadata:
        displayName: ecs-namespace
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: EMC Elastic Cloud Storage (ECS) Namespace for managing Amazon S3, Swift or Atmos buckets.
        providerDisplayName: EMC Corporation
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: 09cac5b8-1b0a-11e6-b6ba-3e1d05defe78
          name: 5gb
          description: Free Trial
          service-settings:
            quota:
              limit: 5
              warning: 4
          metadata:
            costs:
              - amount:
                  usd: 5.0
                unit: MONTHLY
            bullets:
              - Multiple Bucket Namespace
              - 5 GB Storage
              - S3 protocol and HDFS access
    - id: f3cbab6a-5172-4ff1-a5c7-72990f0ce2aa
      name: ecs-bucket
      type: bucket
      description: Elastic Cloud S3 Object Storage Bucket
      bindable: true
      plan-updatable: true
      tags:
        - s3
      service-settings:
        service-type: bucket
        head-type: s3
        file-access: false
        access-during-outage: true
      metadata:
        displayName: ecs-bucket
        imageUrl: http://www.emc.com/images/products/header-image-icon-ecs.png
        longDescription: EMC Elastic Cloud Storage (ECS) Object bucket for storing data using Amazon S3, Swift or Atmos protocols.
        providerDisplayName: EMC Corporation
        documentationUrl: https://community.emc.com/docs/DOC-45012
        supportUrl: http://www.emc.com/products-solutions/trial-software-download/ecs.htm
      plans:
        - id: 8e777d49-0a78-4cf4-810a-b5f5173b019d
          name: 5gb
          description: Free Trial
          service-settings:
            quota:
              limit: 5
              warning: 4
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            bullets:
              - Shared object storage
              - 5 GB Storage
              - S3 protocol and HDFS access
        - id: 89d20694-9ab0-4a98-bc6a-868d6d4ecf31
          name: unlimited
          description: Pay per GB for Month
          metadata:
            costs:
              - amount:
                  usd: 0.03
                unit: PER GB PER MONTH
            bullets:
              - Shared object storage
              - Unlimited Storage
              - S3 protocol and HDFS access
